pipeline:
  identifier: Build_RamyaSubramanian86_harness_1713782133365
  name: Build harness
  orgIdentifier: default
  projectIdentifier: Test
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1713703952734
        repoName: RamyaSubramanian86/harness
        build: <+input>
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_java_app
                  name: Build Java App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      mvn -B package --file pom.xml
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    connectorRef: account.harnessImage
                    repo: ramyameena/test_1
                    tags:
                      - latest
                    caching: true
                  timeout: ""
                  type: BuildAndPushDockerRegistry
              - step:
                  type: BuildAndPushECR
                  name: BuildAndPushECR_2
                  identifier: BuildAndPushECR_2
                  spec:
                    connectorRef: account.AWS_Connector
                    region: us-east-1
                    account: "637423207302"
                    imageName: ramya_test1
                    tags:
                      - version1
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
    - stage:
        name: Approval
        identifier: Approval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: Harness_approval
                  identifier: Harness_approval
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - Approval_group
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
